### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by cyamonide**
This PR updates the README to include explanations on input/output, examples, and links to other helpful references.

🚧 do not merge - still testing examples for correctness
~All examples are tested.~

### CODE REVIEW

**Comment by gagoar** [comment]
looks good for now, I wonder if you could include the defaults we are providing already in the [action.yml](https://github.com/gagoar/invoke-aws-lambda/blob/15b1473a1490fd236ffeac6c025fb9e9e79b2230/action.yml)

**Comment by cyamonide** [comment]
> looks really good. I wonder if you could include the defaults we are providing already in the [action.yml](https://github.com/gagoar/invoke-aws-lambda/blob/15b1473a1490fd236ffeac6c025fb9e9e79b2230/action.yml)

Sure - I'll add required and defaults.

Question about the credentials fields:
image

Is it true that if a user wanted to provide a session token instead of the access key ID/secret access key pair, they wouldn't be able to because the ID/secret pair is required?

**Comment by gagoar** [comment]
> > looks really good. I wonder if you could include the defaults we are providing already in the [action.yml](https://github.com/gagoar/invoke-aws-lambda/blob/15b1473a1490fd236ffeac6c025fb9e9e79b2230/action.yml)
> 
> @gagoar sure - I'll add required and defaults.
> 
> Question about the credentials fields:
> image
> 
> Is it true that if a user wanted to provide a session token instead of the access key ID/secret access key pair, they wouldn't be able to because the ID/secret pair is required?

the configuration ask you for that right now, we can change that just changing the `required: false`

also this is why I've configure them that way, https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html

**Comment by gagoar** [comment]
@cyamonide the signature for the sdk doesn't make the `accessKeyId` or `secretAccessKey` optional. 
  Screen Shot 2020-05-25 at 12 24 49 PM

I think is optional because when it fetches it will sign the request with the session token if present but it will not remove the need for the other 2 attributes.

**Comment by gagoar** [comment]
when you are writing your examples do you mind testing it with `invoke-aws-lambda@master` instead of using `v3`?

**Pull request merged**
