### PR TITLE
Ensure that AWS inputs are masked as secrets

### PR DESCRIPTION
**Pull request by burz**
Using `setSecret` on the value of the secret provided as an input ensures that GitHub's runner will mask the value anywhere it shows up in logs.

Fixes https://github.com/gagoar/invoke-aws-lambda/issues/219

References:
* [`setSecret` docs](https://github.com/actions/toolkit/tree/main/packages/core#setting-a-secret)

### CODE REVIEW

**Comment by gagoar** [comment]
Working on the main branch, taking this moment to add all the updates pending.  I will ping you when this is done.

**Comment by gagoar** [comment]
Thanks for the code, It seems we are okay here, with the change, given that nobody needs to change their workflows to keep operating with this. Could you rebase with master? I will allow the workflows to run once that is done! 

Thanks again!

**Comment by burz** [comment]
Hey @gagoar, sorry I was away at a conference. I will see if I can fix the tests today. Thanks for the ping

**Comment by burz** [comment]
I was able to fix the tests after mocking `setSecret`, afaict the checks should all pass now. Thanks for your help @gagoar!

**Comment by gagoar** [comment]
> I was able to fix the tests after mocking `setSecret`, afaict the checks should all pass now. Thanks for your help @gagoar!
please take a look at the coverage, it seems that L38 is not covered.

**Comment by gagoar** [comment]
> > I was able to fix the tests after mocking `setSecret`, afaict the checks should all pass now. Thanks for your help @gagoar!
> > please take a look at the coverage, it seems that L38 is not covered.

It seems that you would need to make a `it` with the same than the others but providing a `AWS_SESSION_TOKEN` as one of the inputs.

**Comment by burz** [comment]
I've added a test to ensure that we test workflow where `AWS_SESSION_TOKEN` is set.

**Pull request merged**
